name: Inject Secret and Deploy
on:
  push:
    branches: [main] # Runs every time you push code

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject Secret URL into script.js
        run: |
          sed -i 's|PUT_SHEET_URL_HERE|${{ secrets.APPS_SCRIPT_URL }}|g' script.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages